### ISSUE TITLE
SPIRV-tools doesn't build

### ISSUE THREAD

**Issue by mattgodbolt** [compiler-explorer/misc-builder#28]
Latest spirv-tools:

```
$ find /opt/compiler-explorer/SPIRV-Tools-master/ -name spirv-dis 
$
```

there's no spirv-dis and nothing executable other than python and other stuff.

@jzzheng22  any ideas on this? I'm not quite sure what's going on. Let me know if there's any information I need to supply to make this easier - I just untarred the latest built tarball and there's not an obvious exeutable inside.

**Comment by jzzheng22** [comment]
Thanks - I'll take a look when I can but won't have time this week unfortunately.
